### ISSUE TITLE
Publish to maven repository

### ISSUE THREAD

**Issue by giapvokt** [gentics/graphql-java-filter#1]
I very interesting this project and want to use in my project but I dont wat to clone your source code and put it in my project because of it look like I'm stealing your code. So can you pusblish the code to the maven repository so I can use it as a dependancy library. Thank so much

**Comment by philippguertler** [comment]
Thanks for your interest. I'm not experienced in publishing code to the maven central repository. I shortly looked into it and it seemed to be a more time consuming process. It's something I definitely want to do when I can find the time.

In the meantime, you can use jitpack to use this library as a dependency: https://jitpack.io/#gentics/graphql-java-filter/1.0.2

**Comment by giapvokt** [comment]
@philippguertler That great. Thanks
