### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by benmccann** [gentics/graphql-java-filter#2]
Thanks for making this available! It looks very cool

I had a few questions as I was trying to figure out how I might be able to use this:
* The sample on the readme refers to `schema`, `nodes`, `fields`, and `elements`. Are each of these generic attributes that will be used with any project or are they specific to the sample schema?
* Is the source code available for https://demo.getmesh.io/api/v1/demo/graphql/browser?
* Is there an example that defines the schema in a schema file?
* Can you filter for present / not present?
* Can you do a filter equivalent to SQL's `WHERE IN`?
* Is there a way to specify something like an inner join? (Hasura has some good examples of this)

Thanks so much!

**Comment by sandeepgholve** [comment]
Thank you very much for this library, it really helps to start using graphql for query along with powerful filtering options.

@benmccann source code for  https://demo.getmesh.io/api/v1/demo/graphql/browser is here: https://github.com/gentics/mesh.git. ...Even, I was looking for it and found it under parent repo "genetics".

**Comment by philippguertler** [comment]
> The sample on the readme refers to schema, nodes, fields, and elements. Are each of these generic attributes that will be used with any project or are they specific to the sample schema?

These are just examples.

> Is the source code available for https://demo.getmesh.io/api/v1/demo/graphql/browser?
Yes, @sandeepgholve already pointed that out. More specifically, you can look it up here:
https://github.com/gentics/mesh/blob/4d706728bb6d18d6a87c2196f0283b9943ac83f1/verticles/graphql/src/main/java/com/gentics/mesh/graphql/type/QueryTypeProvider.java#L452-L453

This uses the UserFilter:
https://github.com/gentics/mesh/blob/dc29d0ca0b8e4f359df6181324f9c2bd23d11f4d/verticles/graphql/src/main/java/com/gentics/mesh/graphql/filter/UserFilter.java

The UserFilter uses this library.

> Is there an example that defines the schema in a schema file?

No, we generate the schema dynamically using graphql-java.

> Can you filter for present / not present?

Many of the predefined basic filters have an `isNull` filter.

> Can you do a filter equivalent to SQL's WHERE IN?

The StringFilter has a `oneOf` filter which works like a WHERE IN with a list.

> Is there a way to specify something like an inner join? (Hasura has some good examples of this)

You would have to define that in your filter yourself. [Here is an example](https://demo.getmesh.io/api/v2/demo/graphql/browser/#query=%7B%0A%20%20nodes(filter%3A%20%7B%0A%20%20%20%20schema%3A%20%7B%0A%20%20%20%20%20%20name%3A%20%7Bequals%3A%20%22vehicle%22%7D%0A%20%20%20%20%7D%0A%20%20%7D)%20%7B%0A%20%20%20%20elements%20%7B%0A%20%20%20%20%20%20...%20on%20vehicle%20%7B%0A%20%20%20%20%20%20%20%20uuid%0A%20%20%20%20%20%20%20%20fields%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) in our product. Internally this "inner joins" nodes to its schema and queries for the schema name.
Here is the code for this filter: https://github.com/gentics/mesh/blob/8f3492bc6e8889633fa9f8636760804369a50aac/verticles/graphql/src/main/java/com/gentics/mesh/graphql/filter/NodeFilter.java
